### ISSUE TITLE
Open to donations?

### ISSUE THREAD

**Issue by akvashi24** [richfromm/slack2discord#22]
Hi Rich.  Not sure what the best avenue to go about communicating with you is and I know @thomasloupe was instrumental in this project.  I just wanted to let you know that I used slack2discord (with some modifications) to upload ~15k messages from a Slack export to Discord.  I'm very appreciative of your time working on this project and would love to contribute a small donation to you for your work.  It wouldn't be much but I'd like to show some appreciation.  Thanks again for putting time into this.

**Comment by waocats** [comment]
I'd be interested in this as well. We used this for a multi-university research project and would have lost years worth of notes without your help. I'd at least like to buy you a coffee for all of your hard work :)

**Comment by richfromm** [comment]
So sorry for ignoring this issue (and other issues) for so long. I had initially misconfigured the repo so that I was missing notifications for PRs. I thought I had fixed that, but it looks like my fix was incomplete -- I was getting PR notifications, but not issue notifications. So I didn't notice this issue (or any of the other open issues) for months, until just now, as I returned to this to close out the open PRs. I'm embarrassed, esp. when the topic of the issue is asking about donations. Sorry again, I didn't mean to be rude and just ignore everybody.

Anyway, I have no experience with this, so I'm researching the best way to do this. GitHub Sponsors sounds okay in theory, except for the fact that they are apparently on the verge of removing PayPal as an option. So a simple PayPal donation link in the README may be the way that I go.

So if you're still interested after all of this elapsed time, you can wait until I decide what to do (hopefully sometime this week), or in the meantime feel free to send a donation via PayPal to paypal <at> richard <dot> fromm <dot> name

And speaking as yet another SF Bay area laid off tech worker, I'm also very happy to accept leads on job interviews as a donation. :)

**Comment by akvashi24** [comment]
@richfromm Thanks so much for the response, and don't beat yourself up.  I'll be sending a donation via paypal.  I'm also happy to give you a referral!!  Please reach out to akvashi24 at gmail!

**Comment by richfromm** [comment]
Donation options are now set up:
https://github.com/richfromm/slack2discord/pull/34/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

That's still on a branch, will probably close the PR and merge it tomorrow, at which point it should appear on the main project page.

**Comment by richfromm** [comment]
Donation buttons are now live, as of the 2.6 release
